import Route from '@ember/routing/route';

export default class AboutRoute extends Route {
  model() {
    return [
      { name: 'Aaron R. Brown' },
      { name: 'Ali Cat' },
      { name: 'AnawesomewavE' },
      { name: 'Axl Herevia' },
      { name: 'Anthony Volodkin' },
      { name: 'ben franchuk' },
      { name: 'Braxton' },
      { name: 'Casey Primozic' },
      { name: 'Casey VanAntwerp' },
      { name: 'calgames' },
      { name: 'Chris Romero' },
      { name: 'claire rennard' },
      { name: 'Dannel Jurado' },
      { name: 'DJ oven' },
      { name: 'Drongo Unchained' },
      { name: 'E G' },
      { name: 'Erin tanner' },
      { name: 'Evan Higgins' },
      { name: 'five star hotel' },
      { name: 'Gaiety' },
      { name: 'Gia' },
      { name: 'Ginger Steve' },
      { name: 'GLORIA and KEN' },
      { name: 'Izzy J' },
      { name: 'Jeffrey Hawkins' },
      { name: 'Jesse Erickson' },
      { name: 'kat' },
      { name: 'KILLED in CARS' },
      { name: 'Lucija' },
      { name: 'Lindsay Coulter' },
      { name: 'Mary Hourani' },
      { name: 'Nicholas Subramaniam' },
      { name: 'Phil Montville' },
      { name: 'Ross' },
      { name: 'Ronan' },
      { name: 'Sean' },
      { name: 'sofie mikhaylova' },
      { name: 'STRIDER' },
      { name: 'Takashi Kawano' },
      { name: 'takuma chiba' },
      { name: 'Tank Jr.' },
      { name: 'Timelord SFX' },
      { name: 'Veepy' },
    ];
  }
}
