import Route from '@ember/routing/route';

export default class AboutRoute extends Route {
  model() {
    return [
      { name: 'Aaron R. Brown' },
      { name: 'Ali Cat' },
      { name: 'AnawesomewavE' },
      { name: 'Axl Herevia' },
      { name: 'Anthony Volodkin' },
      { name: 'ben franchuk' },
      { name: 'Braxton' },
      { name: 'Brady King' },
      { name: 'Casey Primozic' },
      { name: 'Casey VanAntwerp' },
      { name: 'calgames' },
      { name: 'Chris Romero' },
      { name: 'Chaohord' },
      { name: 'claire rennard' },
      { name: 'Dannel Jurado' },
      { name: 'DJCrabhat' },
      { name: 'DJ oven' },
      { name: 'Drongo Unchained' },
      { name: 'E G' },
      { name: 'Erin tanner' },
      { name: 'Evan Higgins' },
      { name: 'five star hotel' },
      { name: 'Gaiety' },
      { name: 'Gia' },
      { name: 'Ginger Steve' },
      { name: 'GLORIA and KEN' },
      { name: 'Gerogio Soros' },
      { name: 'gutter' },
      { name: 'Izzy J' },
      { name: 'infotoxin' },
      { name: 'Jake Dempsey' },
      { name: 'Jeffrey Hawkins' },
      { name: 'Jesse Erickson' },
      { name: 'Jin' },
      { name: 'Jose' },
      { name: 'Josh' },
      { name: 'kat' },
      { name: 'KILLED in CARS' },
      { name: 'kpiss' },
      { name: 'Lucija' },
      { name: 'Lindsay Coulter' },
      { name: 'LLTH' },
      { name: 'Michael Lykins' },
      { name: 'Michael Larkin' },
      { name: 'Nicholas Subramaniam' },
      { name: 'Mitsuko Endo' },
      { name: 'Mr. Busy' },
      { name: 'noah' },
      { name: 'Phil Montville' },
      { name: 'pigeon' },
      { name: 'Ross' },
      { name: 'Ronan' },
      { name: 'Sam Raymer' },
      { name: 'Sean' },
      { name: 'seph' },
      { name: 'sofie mikhaylova' },
      { name: 'sr388' },
      { name: 'STRIDER' },
      { name: 'Takashi Kawano' },
      { name: 'takuma chiba' },
      { name: 'Tank Jr.' },
      { name: 'Timelord SFX' },
      { name: 'Trai W' },
      { name: 'Veepy' },
    ];
  }
}
